# Indeed Auto-Apply Bot Configuration
# Edit these fields to customize your job search and application process


search:
  base_url: "https://fr.indeed.com/jobs?q=developer&l=Ile-de-France&sc=0kf%3Aattr%285QWDV%29%3B&radius=25"

  start: 0
  end: 100 # default is 100, you can set it to 1000 or more for larger searches (not recommanded though)

camoufox:
  user_data_dir: "user_data_dir"
  language: "fr" # uk, us, fr, de, es, it, nl, pt, pl, ro, tr, ru, cn etc...





